import fs from 'fs/promises'
import path from 'path'

export async function buildProject(type, name) {
  if (!name) {
    console.error('❌ Please provide a project name.')
    return false
  }

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const projectDir = path.join(process.cwd(), 'projects', `${type}-${slug}`)

  try {
    await fs.mkdir(projectDir, { recursive: true })
  } catch (err) {
    console.error('❌ Could not create project folder:', err.message)
    return false
  }

  console.log(`📁 Created project folder: ${projectDir}`)

  if (type === 'landing-page') {
    await fs.writeFile(path.join(projectDir, 'index.html'), landingPageHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), landingPageCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nLanding page generated by SPECTRE.\n`)
  } else if (type === 'portfolio') {
    await fs.writeFile(path.join(projectDir, 'index.html'), portfolioHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), portfolioCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nPortfolio generated by SPECTRE.\n`)
  } else if (type === 'dashboard') {
    await fs.writeFile(path.join(projectDir, 'index.html'), dashboardHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), dashboardCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nDashboard generated by SPECTRE.\n`)
  } else if (type === 'contact-form') {
    await fs.writeFile(path.join(projectDir, 'index.html'), contactFormHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), contactFormCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nContact form generated by SPECTRE.\n`)
  } else if (type === 'blog') {
    await fs.writeFile(path.join(projectDir, 'index.html'), blogHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), blogCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nBlog generated by SPECTRE.\n`)
  } else if (type === 'api-starter') {
    await fs.writeFile(path.join(projectDir, 'index.js'), apiStarterJS(name))
    await fs.writeFile(path.join(projectDir, 'package.json'), apiStarterPackage(name))
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nAPI starter generated by SPECTRE.\n`)
  } else if (type === 'automation') {
    await fs.writeFile(path.join(projectDir, 'script.js'), automationJS(name))
    await fs.writeFile(path.join(projectDir, 'config.json'), automationConfig())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nAutomation script generated by SPECTRE.\n`)
  } else {
    console.error(`❌ Unknown project type: ${type}`)
    return false
  }

  console.log('✅ SPECTRE built the project scaffold.')
  return true
}

function landingPageHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Your trusted local service</p>
  </header>

  <main>
    <section class="hero">
      <h2>We help customers find you</h2>
      <p>Fast, reliable, and local.</p>
      <a href="#contact" class="cta">Get in touch</a>
    </section>

    <section id="contact">
      <h2>Contact Us</h2>
      <form>
        <input type="text" placeholder="Your name" required />
        <input type="email" placeholder="Your email" required />
        <textarea placeholder="Your message"></textarea>
        <button type="submit">Send</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function landingPageCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: #1e293b;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

header h1 {
  font-size: 2rem;
}

.hero {
  text-align: center;
  padding: 3rem 1rem;
  background: #f8fafc;
}

.hero h2 {
  margin-bottom: 0.5rem;
}

.cta {
  display: inline-block;
  margin-top: 1rem;
  padding: 0.75rem 1.5rem;
  background: #0ea5e9;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
}

#contact {
  padding: 2rem 1rem;
  max-width: 600px;
  margin: 0 auto;
}

#contact form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

#contact input,
#contact textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

#contact button {
  padding: 0.75rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}

function portfolioHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Portfolio</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>My work and projects</p>
  </header>

  <main>
    <section class="intro">
      <h2>About Me</h2>
      <p>Brief introduction goes here. Replace with your own story.</p>
    </section>

    <section class="projects">
      <h2>Selected Work</h2>
      <div class="card">
        <h3>Project One</h3>
        <p>Short description of this project.</p>
      </div>
      <div class="card">
        <h3>Project Two</h3>
        <p>Short description of this project.</p>
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function portfolioCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: #0f172a;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

main {
  padding: 2rem 1rem;
  max-width: 800px;
  margin: 0 auto;
}

.intro {
  margin-bottom: 2rem;
}

.projects .card {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 1rem;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #0f172a;
  color: #fff;
}`
}

function dashboardHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Dashboard</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Command center</p>
  </header>

  <main class="dashboard">
    <div class="card">
      <h3>📊 Stat One</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📈 Stat Two</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📅 Stat Three</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📋 Stat Four</h3>
      <p>Value</p>
    </div>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function dashboardCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f1f5f9;
  color: #333;
}

header {
  background: #0f172a;
  color: #fff;
  padding: 1rem;
  text-align: center;
}

.dashboard {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  padding: 2rem;
}

.card {
  background: #fff;
  border-radius: 8px;
  padding: 1.5rem;
  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

footer {
  text-align: center;
  padding: 1rem;
  background: #0f172a;
  color: #fff;
}`
}

function contactFormHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Contact</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>We'd love to hear from you</p>
  </header>

  <main>
    <form>
      <input type="text" placeholder="Your name" required />
      <input type="email" placeholder="Your email" required />
      <select>
        <option>General inquiry</option>
        <option>Support</option>
        <option>Partnership</option>
      </select>
      <textarea placeholder="Your message" rows="5" required></textarea>
      <button type="submit">Send message</button>
    </form>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function contactFormCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f8fafc;
  color: #333;
}

header {
  background: #1e293b;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

main {
  max-width: 600px;
  margin: 2rem auto;
  padding: 0 1rem;
}

form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

input, select, textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

button {
  padding: 0.75rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}

function blogHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Blog</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Thoughts and updates</p>
  </header>

  <main>
    <article>
      <h2>First Post</h2>
      <p>This is where your content goes. Replace with your own story.</p>
    </article>

    <article>
      <h2>Second Post</h2>
      <p>Another post placeholder. Keep your readers engaged.</p>
    </article>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function blogCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Georgia, serif;
  line-height: 1.8;
  color: #222;
  background: #fafaf5;
}

header {
  text-align: center;
  padding: 2rem 1rem;
  border-bottom: 1px solid #ddd;
}

main {
  max-width: 700px;
  margin: 2rem auto;
  padding: 0 1rem;
}

article {
  margin-bottom: 3rem;
}

h2 {
  margin-bottom: 0.5rem;
}

footer {
  text-align: center;
  padding: 1rem;
  border-top: 1px solid #ddd;
}`
}

function apiStarterJS(name) {
  return `import express from 'express'
const app = express()
const port = process.env.PORT || 3000

app.get('/', (req, res) => {
  res.json({ message: '${name} API is running' })
})

app.listen(port, () => {
  console.log('${name} API listening on port ' + port)
})`
}

function apiStarterPackage(name) {
  return JSON.stringify({
    name: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    version: '1.0.0',
    type: 'module',
    main: 'index.js',
    scripts: {
      start: 'node index.js'
    },
    dependencies: {
      express: '^4.18.2'
    }
  }, null, 2)
}

function automationJS(name) {
  return `// ${name} — Automation script
import fs from 'fs/promises'
import config from './config.json' with { type: 'json' }

async function main() {
  console.log('Running ${name} automation...')
  console.log('Config loaded:', config)

  // TODO: Add your automation logic here

  console.log('Done.')
}

main().catch(console.error)`
}

function automationConfig() {
  return JSON.stringify({
    name: 'Automation config',
    version: '1.0.0',
    tasks: []
  }, null, 2)
}