import fs from 'fs/promises'
import path from 'path'

export async function buildProject(type, name) {
  if (!name) {
    console.error('❌ Please provide a project name.')
    return false
  }

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const projectDir = path.join(process.cwd(), 'projects', `${type}-${slug}`)

  try {
    await fs.mkdir(projectDir, { recursive: true })
  } catch (err) {
    console.error('❌ Could not create project folder:', err.message)
    return false
  }

  console.log(`📁 Created project folder: ${projectDir}`)

  if (type === 'landing-page') {
    await fs.writeFile(path.join(projectDir, 'index.html'), landingPageHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), landingPageCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nLanding page generated by SPECTRE.\n`)
  } else if (type === 'portfolio') {
    await fs.writeFile(path.join(projectDir, 'index.html'), portfolioHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), portfolioCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nPortfolio generated by SPECTRE.\n`)
  } else if (type === 'dashboard') {
    await fs.writeFile(path.join(projectDir, 'index.html'), dashboardHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), dashboardCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nDashboard generated by SPECTRE.\n`)
  } else if (type === 'contact-form') {
    await fs.writeFile(path.join(projectDir, 'index.html'), contactFormHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), contactFormCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nContact form generated by SPECTRE.\n`)
  } else if (type === 'blog') {
    await fs.writeFile(path.join(projectDir, 'index.html'), blogHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), blogCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nBlog generated by SPECTRE.\n`)
  } else if (type === 'api-starter') {
    await fs.writeFile(path.join(projectDir, 'index.js'), apiStarterJS(name))
    await fs.writeFile(path.join(projectDir, 'package.json'), apiStarterPackage(name))
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nAPI starter generated by SPECTRE.\n`)
  } else if (type === 'automation') {
    await fs.writeFile(path.join(projectDir, 'script.js'), automationJS(name))
    await fs.writeFile(path.join(projectDir, 'config.json'), automationConfig())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nAutomation script generated by SPECTRE.\n`)
  } else if (type === 'pricing') {
    await fs.writeFile(path.join(projectDir, 'index.html'), pricingHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), pricingCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nPricing page generated by SPECTRE.\n`)
  } else if (type === 'faq') {
    await fs.writeFile(path.join(projectDir, 'index.html'), faqHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), faqCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nFAQ page generated by SPECTRE.\n`)
  } else if (type === 'coming-soon') {
    await fs.writeFile(path.join(projectDir, 'index.html'), comingSoonHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), comingSoonCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nComing soon page generated by SPECTRE.\n`)
  } else if (type === 'bio-link') {
    await fs.writeFile(path.join(projectDir, 'index.html'), bioLinkHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), bioLinkCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nBio link page generated by SPECTRE.\n`)
  } else if (type === 'documentation') {
    await fs.writeFile(path.join(projectDir, 'index.html'), documentationHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), documentationCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nDocumentation generated by SPECTRE.\n`)
  } else {
    console.error(`❌ Unknown project type: ${type}`)
    return false
  }

  console.log('✅ SPECTRE built the project scaffold.')
  return true
}

function landingPageHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Your trusted local service</p>
  </header>

  <main>
    <section class="hero">
      <h2>We help customers find you</h2>
      <p>Fast, reliable, and local.</p>
      <a href="#contact" class="cta">Get in touch</a>
    </section>

    <section id="contact">
      <h2>Contact Us</h2>
      <form>
        <input type="text" placeholder="Your name" required />
        <input type="email" placeholder="Your email" required />
        <textarea placeholder="Your message"></textarea>
        <button type="submit">Send</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function landingPageCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: #1e293b;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

header h1 {
  font-size: 2rem;
}

.hero {
  text-align: center;
  padding: 3rem 1rem;
  background: #f8fafc;
}

.hero h2 {
  margin-bottom: 0.5rem;
}

.cta {
  display: inline-block;
  margin-top: 1rem;
  padding: 0.75rem 1.5rem;
  background: #0ea5e9;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
}

#contact {
  padding: 2rem 1rem;
  max-width: 600px;
  margin: 0 auto;
}

#contact form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

#contact input,
#contact textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

#contact button {
  padding: 0.75rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}

function portfolioHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Portfolio</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>My work and projects</p>
  </header>

  <main>
    <section class="intro">
      <h2>About Me</h2>
      <p>Brief introduction goes here. Replace with your own story.</p>
    </section>

    <section class="projects">
      <h2>Selected Work</h2>
      <div class="card">
        <h3>Project One</h3>
        <p>Short description of this project.</p>
      </div>
      <div class="card">
        <h3>Project Two</h3>
        <p>Short description of this project.</p>
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function portfolioCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: #0f172a;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

main {
  padding: 2rem 1rem;
  max-width: 800px;
  margin: 0 auto;
}

.intro {
  margin-bottom: 2rem;
}

.projects .card {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 1rem;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #0f172a;
  color: #fff;
}`
}

function dashboardHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Dashboard</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Command center</p>
  </header>

  <main class="dashboard">
    <div class="card">
      <h3>📊 Stat One</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📈 Stat Two</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📅 Stat Three</h3>
      <p>Value</p>
    </div>
    <div class="card">
      <h3>📋 Stat Four</h3>
      <p>Value</p>
    </div>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function dashboardCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f1f5f9;
  color: #333;
}

header {
  background: #0f172a;
  color: #fff;
  padding: 1rem;
  text-align: center;
}

.dashboard {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  padding: 2rem;
}

.card {
  background: #fff;
  border-radius: 8px;
  padding: 1.5rem;
  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

footer {
  text-align: center;
  padding: 1rem;
  background: #0f172a;
  color: #fff;
}`
}

function contactFormHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Contact</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>We'd love to hear from you</p>
  </header>

  <main>
    <form>
      <input type="text" placeholder="Your name" required />
      <input type="email" placeholder="Your email" required />
      <select>
        <option>General inquiry</option>
        <option>Support</option>
        <option>Partnership</option>
      </select>
      <textarea placeholder="Your message" rows="5" required></textarea>
      <button type="submit">Send message</button>
    </form>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function contactFormCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f8fafc;
  color: #333;
}

header {
  background: #1e293b;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

main {
  max-width: 600px;
  margin: 2rem auto;
  padding: 0 1rem;
}

form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

input, select, textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

button {
  padding: 0.75rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}

function blogHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Blog</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Thoughts and updates</p>
  </header>

  <main>
    <article>
      <h2>First Post</h2>
      <p>This is where your content goes. Replace with your own story.</p>
    </article>

    <article>
      <h2>Second Post</h2>
      <p>Another post placeholder. Keep your readers engaged.</p>
    </article>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function blogCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Georgia, serif;
  line-height: 1.8;
  color: #222;
  background: #fafaf5;
}

header {
  text-align: center;
  padding: 2rem 1rem;
  border-bottom: 1px solid #ddd;
}

main {
  max-width: 700px;
  margin: 2rem auto;
  padding: 0 1rem;
}

article {
  margin-bottom: 3rem;
}

h2 {
  margin-bottom: 0.5rem;
}

footer {
  text-align: center;
  padding: 1rem;
  border-top: 1px solid #ddd;
}`
}

function apiStarterJS(name) {
  return `import express from 'express'
const app = express()
const port = process.env.PORT || 3000

app.get('/', (req, res) => {
  res.json({ message: '${name} API is running' })
})

app.listen(port, () => {
  console.log('${name} API listening on port ' + port)
})`
}

function apiStarterPackage(name) {
  return JSON.stringify({
    name: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    version: '1.0.0',
    type: 'module',
    main: 'index.js',
    scripts: {
      start: 'node index.js'
    },
    dependencies: {
      express: '^4.18.2'
    }
  }, null, 2)
}

function automationJS(name) {
  return `// ${name} — Automation script
import fs from 'fs/promises'
import config from './config.json' with { type: 'json' }

async function main() {
  console.log('Running ${name} automation...')
  console.log('Config loaded:', config)

  // TODO: Add your automation logic here

  console.log('Done.')
}

main().catch(console.error)`
}

function automationConfig() {
  return JSON.stringify({
    name: 'Automation config',
    version: '1.0.0',
    tasks: []
  }, null, 2)
}

function pricingHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Pricing</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Choose your plan</p>
  </header>

  <main class="pricing">
    <div class="plan">
      <h2>Basic</h2>
      <p class="price">$9/mo</p>
      <ul>
        <li>Feature one</li>
        <li>Feature two</li>
      </ul>
      <button>Choose</button>
    </div>
    <div class="plan featured">
      <h2>Pro</h2>
      <p class="price">$19/mo</p>
      <ul>
        <li>Everything in Basic</li>
        <li>Feature three</li>
        <li>Feature four</li>
      </ul>
      <button>Choose</button>
    </div>
    <div class="plan">
      <h2>Enterprise</h2>
      <p class="price">$49/mo</p>
      <ul>
        <li>Everything in Pro</li>
        <li>Priority support</li>
      </ul>
      <button>Choose</button>
    </div>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function pricingCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f8fafc;
  color: #333;
}

header {
  text-align: center;
  padding: 2rem;
  background: #0f172a;
  color: #fff;
}

.pricing {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1.5rem;
  padding: 2rem;
}

.plan {
  background: #fff;
  padding: 2rem;
  border-radius: 10px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.08);
  text-align: center;
}

.plan.featured {
  border: 2px solid #0ea5e9;
}

.price {
  font-size: 1.5rem;
  margin: 0.5rem 0;
}

.plan ul {
  list-style: none;
  margin: 1rem 0;
}

.plan li {
  margin: 0.25rem 0;
}

.plan button {
  padding: 0.5rem 1.25rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #0f172a;
  color: #fff;
}`
}

function faqHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — FAQ</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Frequently asked questions</p>
  </header>

  <main>
    <div class="faq">
      <h3>What is this?</h3>
      <p>This is a simple FAQ answer. Replace with your own content.</p>
    </div>
    <div class="faq">
      <h3>How does it work?</h3>
      <p>Explain the process here. Keep it clear and brief.</p>
    </div>
    <div class="faq">
      <h3>How much does it cost?</h3>
      <p>Answer pricing questions or point to your pricing page.</p>
    </div>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function faqCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f8fafc;
  color: #333;
}

header {
  text-align: center;
  padding: 2rem;
  background: #1e293b;
  color: #fff;
}

main {
  max-width: 700px;
  margin: 2rem auto;
  padding: 0 1rem;
}

.faq {
  background: #fff;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1rem;
  box-shadow: 0 1px 4px rgba(0,0,0,0.08);
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}

function comingSoonHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Coming Soon</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <main>
    <h1>${name}</h1>
    <p>Something great is on the way.</p>
    <form>
      <input type="email" placeholder="Enter your email" required />
      <button type="submit">Notify me</button>
    </form>
  </main>
</body>
</html>`
}

function comingSoonCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: linear-gradient(135deg, #0f172a, #1e293b);
  color: #fff;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
}

main {
  padding: 2rem;
}

h1 {
  font-size: 3rem;
  margin-bottom: 0.5rem;
}

form {
  margin-top: 2rem;
}

input {
  padding: 0.75rem;
  border-radius: 5px;
  border: none;
  width: 250px;
}

button {
  padding: 0.75rem 1.25rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  margin-left: 0.5rem;
}`
}

function bioLinkHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <main>
    <img src="https://via.placeholder.com/100" alt="avatar" class="avatar" />
    <h1>${name}</h1>
    <p>Links and updates</p>
    <a href="#" class="link">Website</a>
    <a href="#" class="link">YouTube</a>
    <a href="#" class="link">Facebook</a>
    <a href="#" class="link">Contact</a>
  </main>
</body>
</html>`
}

function bioLinkCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #f8fafc;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  text-align: center;
}

main {
  padding: 2rem;
  max-width: 400px;
}

.avatar {
  border-radius: 50%;
  margin-bottom: 1rem;
}

.link {
  display: block;
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 10px;
  padding: 1rem;
  margin: 0.75rem 0;
  text-decoration: none;
  color: #333;
  font-weight: bold;
}

.link:hover {
  background: #f1f5f9;
}`
}

function documentationHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Documentation</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <aside>
    <h2>${name}</h2>
    <ul>
      <li><a href="#intro">Introduction</a></li>
      <li><a href="#setup">Setup</a></li>
      <li><a href="#usage">Usage</a></li>
    </ul>
  </aside>

  <main>
    <section id="intro">
      <h1>Introduction</h1>
      <p>Welcome to the documentation. Replace with your own content.</p>
    </section>
    <section id="setup">
      <h1>Setup</h1>
      <p>Explain how to install or configure your project.</p>
    </section>
    <section id="usage">
      <h1>Usage</h1>
      <p>Show examples or commands.</p>
    </section>
  </main>
</body>
</html>`
}

function documentationCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  display: flex;
  background: #fff;
  color: #333;
}

aside {
  width: 250px;
  background: #0f172a;
  color: #fff;
  min-height: 100vh;
  padding: 2rem 1rem;
}

aside h2 {
  margin-bottom: 1rem;
}

aside ul {
  list-style: none;
}

aside a {
  color: #cbd5e1;
  text-decoration: none;
  display: block;
  padding: 0.5rem 0;
}

aside a:hover {
  color: #fff;
}

main {
  padding: 2rem;
  flex: 1;
}

section {
  margin-bottom: 2rem;
}

h1 {
  margin-bottom: 0.5rem;
}`
}