import fs from 'fs/promises'
import path from 'path'

export async function buildProject(type, name) {
  if (!name) {
    console.error('❌ Please provide a project name.')
    return false
  }

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const projectDir = path.join(process.cwd(), 'projects', `${type}-${slug}`)

  try {
    await fs.mkdir(projectDir, { recursive: true })
  } catch (err) {
    console.error('❌ Could not create project folder:', err.message)
    return false
  }

  console.log(`📁 Created project folder: ${projectDir}`)

  if (type === 'landing-page') {
    await fs.writeFile(path.join(projectDir, 'index.html'), landingPageHTML(name))
    await fs.writeFile(path.join(projectDir, 'style.css'), landingPageCSS())
    await fs.writeFile(path.join(projectDir, 'README.md'), `# ${name}\n\nGenerated by SPECTRE.\n`)
  } else {
    console.error(`❌ Unknown project type: ${type}`)
    return false
  }

  console.log('✅ SPECTRE built the project scaffold.')
  return true
}

function landingPageHTML(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header>
    <h1>${name}</h1>
    <p>Your trusted local service</p>
  </header>

  <main>
    <section class="hero">
      <h2>We help customers find you</h2>
      <p>Fast, reliable, and local.</p>
      <a href="#contact" class="cta">Get in touch</a>
    </section>

    <section id="contact">
      <h2>Contact Us</h2>
      <form>
        <input type="text" placeholder="Your name" required />
        <input type="email" placeholder="Your email" required />
        <textarea placeholder="Your message"></textarea>
        <button type="submit">Send</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; ${new Date().getFullYear()} ${name}. All rights reserved.</p>
  </footer>
</body>
</html>`
}

function landingPageCSS() {
  return `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: #1e293b;
  color: #fff;
  text-align: center;
  padding: 2rem 1rem;
}

header h1 {
  font-size: 2rem;
}

.hero {
  text-align: center;
  padding: 3rem 1rem;
  background: #f8fafc;
}

.hero h2 {
  margin-bottom: 0.5rem;
}

.cta {
  display: inline-block;
  margin-top: 1rem;
  padding: 0.75rem 1.5rem;
  background: #0ea5e9;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
}

#contact {
  padding: 2rem 1rem;
  max-width: 600px;
  margin: 0 auto;
}

#contact form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

#contact input,
#contact textarea {
  padding: 0.75rem;
  border: 1px solid #ccc;
  border-radius: 5px;
}

#contact button {
  padding: 0.75rem;
  background: #0ea5e9;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

footer {
  text-align: center;
  padding: 1rem;
  background: #1e293b;
  color: #fff;
}`
}
